Editable installs
gaborbernat/peps pull request #1
Opened 2021-06-01 08:47 UTC by gaborbernat

👍

2021-06-01 09:34 UTC, pradyunsg commented on pep-9999.rst
> +and `PEP-518`_) and then install that wheel into a python environment.
```suggestion
and `PEP-518`_) and then installing that wheel into a python environment.
```

2021-06-01 10:53 UTC, jugmac00 reviewed
May the packaging gods be with you and the PEP get accepted! :+1:

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +and `PEP-518`_) and then install that wheel into a python environment.
```suggestion
and `PEP-518`_) and then installing that wheel into a Python environment.
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +  this case the user have to install the project dependencies themselves and
```suggestion
  this case the users have to install the project dependencies themselves and
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +- `flit`_ provides the `flit install --symlink`_ command that: symlinks the
```suggestion
- `flit`_ provides the `flit install --symlink`_ command that symlinks the
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +frontend and backends for building and installing projects in editable mode.
Why is it "build frontend" but "build backends"? singular vs plural

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +frontends. The PEP also proposes on not imposing any editable mode onto the
Again `backend` vs `frontends`.

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +frontend to communicate with the build backend).
```suggestion
packaging tool the user communicates with. In turn the packing tool uses the build
frontend to communicate with the build backend).
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +between build backend and frontends we can totally eliminate the need of the
Again: `backend` vs `frontends`.

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +``setup.py`` file and communication method.
What is `and communication method.` referring to?

If this is referring to the **current** communication method between build frontend and backend, maybe rephrase it to 

```suggestion
``setup.py`` file and their current communication method.
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +expectation that source code is imported from the source tree.
I am not sure why there is the second part of the sentence about the user expectation and how this relates to the first part of the sentence with configuration changes. -> ??? for me :-) What is `it` referring to? Why are changes in configuration files consistent with how code is imported? I do not understand the intention of this sentences.

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +behave identically as a regular installation. Depending on the way build build
```suggestion
behave identically as a regular installation. Depending on the way build
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +such as the presence of additional files (compared to a regular installation)
```suggestion
such as the presence of additional files (compared to a regular installation),
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +either in the source tree or the interpreters installation path. Both the build
```suggestion
either in the source tree or the interpreter's installation path. Both the build
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +backend and frontends are encouraged to document such potential differences.
Again: `backend` vs `frontends`

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +For reference a non editable installation works as follows:
```suggestion
For reference, a non editable installation works as follows:
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +   trigger a package build and install of a project they'll communicate with
```suggestion
   trigger a package build and installation of a project they'll communicate with
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +2. The orchestrator uses a **build frontend** to trigger build of a wheel
```suggestion
2. The orchestrator uses a **build frontend** to trigger the build of a wheel
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +   `installer`_) to install the wheel into the target python interpreter.
```suggestion
   `installer`_) to install the wheel into the target Python interpreter.
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +  def build_editable(config_settings=None):
Looks like this is the wrong function name here?

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +``build_editable`` hook.
Just for my personal interest - which dependencies could this be?

Why does an editable install need more/different dependencies than a regular one?

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +      """distribution information of the package as defined by PEP-491"""
I have never seen a docstring for a type annotation - is this common?

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +      """distribution information of the package as defined by PEP-491"""
I have never this a docstring for a type annotation... is this common?

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +      """files or folders that should be available under the purelib"""
I am not familiar with the terms `purelib` and `platlib` - are those terms something worth adding to the "terminology" section? Or are those super familiar for all who will decide on this PEP?

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +backend to generate the build editable information. It's also responsible of
`the build editable information` is this a common term?

if not...

```suggestion
backend to generate the information which is necessary for an editable build. It's also responsible of
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +The orchestrator must ensure that all install requirements (and should the user
```suggestion
The orchestrator must ensure that all installation requirements (and should the user
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +The orchestrator must ensure that console or gui entrypoints are generated
```suggestion
The orchestrator must ensure that console or GUI entrypoints are generated
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +target interpreter.
The above sentence is pretty tough to understand. I suggest do move the contents within in the parenthesis to go at the end and rephrase to `The same applies to ...`.

Also `are installed part of the editable build into the target interpreter.` needs to be rephrased.

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +``.dist-info`` come as part of a wheel.
This sentence is also hard to understand.

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +before any other import mechanisms are attempted.
```suggestion
before any other import mechanisms are executed.
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +guarantee or environment variables. The build backend should generate an import
I do not understand this sentence.

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +hook that does not really on the value of these states.
```suggestion
hook that does not rely on the value of these states.
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +Example editable mode implementations
Until now it was always about "editable installation" - and now there is "editable mode". Is this intended? What is the difference?

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +distribution information.
I do not understand the last part of the sentence. What distribution information? What is a parent of an information?

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +This mode requires the build backend to provides one or more folder(s)/file(s)
```suggestion
This mode requires the build backend to provide one or more folder(s)/file(s)
```

2021-06-01 10:53 UTC, jugmac00 commented on pep-9999.rst
> +use ``pth`` files with this set of information too.
```suggestion
use ``pth`` files with this set of information, too.
```

2021-06-01 11:28 UTC, gaborbernat commented on pep-9999.rst
> +``build_editable`` hook.
In case it has an import-hook the mechanism that generates the import hook might require additional dependency (e.g. the editables pypi project).

2021-06-01 11:28 UTC, gaborbernat commented on pep-9999.rst
> +      """distribution information of the package as defined by PEP-491"""
Can't tell, but definitely can be used.

2021-06-01 11:29 UTC, gaborbernat commented on pep-9999.rst
> +      """files or folders that should be available under the purelib"""
Generally, packaging people are super familiar with it. And is already covered in the linked PEP-491 - https://www.python.org/dev/peps/pep-0491/#what-s-the-deal-with-purelib-vs-platlib

2021-06-01 19:20 UTC, jugmac00 reviewed
As promised...

2021-06-01 19:20 UTC, jugmac00 commented on pep-9999.rst
> +the ecosystem to use alternative mechanisms to achieve the editable install
```suggestion
the ecosystem to use alternative mechanisms to achieve the editable installation
```

2021-06-01 19:20 UTC, jugmac00 commented on pep-9999.rst
> +the loose wheel mode from the backend described by that PEP).
```suggestion
effect (e.g., insert path on ``sys.path`` or symlinks instead of just implying
the loose wheel mode from the backend described by that PEP).
```

2021-06-02 08:19 UTC, gaborbernat commented on pep-9999.rst
> +get_requires_for_build_editable
This follows the format set by PEP-517.

2021-06-02 20:50 UTC, pganssle requested changes
I've only reviewed as far down as my comments go, but I think a lot of the fundamental structural changes are in the parts I did review.

2021-06-02 20:50 UTC, pganssle commented on pep-9999.rst
> +Once the project is installed in editable mode, users expect that changes to the project code in the local source tree become effective without the need for a new installation step.
Some users may expect this, but it is by no means a guarantee (it cannot be guaranteed in general).

Perhaps it would be better to phrase this as, "Once the project is installed in editable mode, some changes to the project code in the local source tree will become effective without the need for a new installation step. At minimum, changes to the text of non-generated files that existed at the time of the installation should be reflected upon the next import of the package."

2021-06-02 20:50 UTC, pganssle commented on pep-9999.rst
> +Some kinds of changes, such as adding or modifying entry points or new dependencies, require a new installation step to become effective. These changes are typically made in build backend configurati
We may want to get into this elsewhere instead. This is one class of changes that may or may not be reflected, depending on the choices of the frontend.

2021-06-02 20:50 UTC, pganssle commented on pep-9999.rst
> +When a project is installed in editable mode, users expect the installation to behave identically as a standard installation. Depending on how a build
It may be best to make it clear that this is almost certainly not possible. In fact, I would start this off as pessimistic, like:

"While users expect editable installations to behave identically to standard installations, this may not always be possible, and may in fact be in tension with other user expectations. Build frontends **should** seek to minimize differences between the behavior of editable and standard installations and document known differences."

2021-06-02 20:50 UTC, pganssle commented on pep-9999.rst
> +2. The frontend uses a **build frontend** to trigger the build of a wheel (e.g., `build`_). The build frontend uses `PEP-517`_ to communicate with the **build backend** (e.g. `setuptools`_) - with th
Are you making a distinction between frontend and build frontend? I don't see why there needs to be a distinction here.

Also, it is probably worth changing from "isolated environment" to `PEP-518` environment or something of that nature, since PEP 518 does allow for using non-isolated environments.

2021-06-02 20:50 UTC, pganssle commented on pep-9999.rst
> +get_requires_for_build_editable
I'm not sure that this hook is necessary. It's why you'd need special editable-only dependencies. I think this may be residue from PEP 660's suggestion of including a special library for doing editable installations.

I probably would leave it out unless someone says they actually need it, but I don't think it's hurting anything, particularly if it's optional.

2021-06-02 20:50 UTC, pganssle commented on pep-9999.rst
> +This hook MUST return an additional list of strings containing `PEP-508`_ dependency specifications, above and beyond those specified in the ``pyproject.toml`` file. These dependencies will be instal
Does it need to be a list? Perhaps sequence?

2021-06-02 20:50 UTC, pganssle commented on pep-9999.rst
> +If not defined, the default implementation is equivalent to return ``[]``.
s/return/returning.

2021-06-02 20:50 UTC, pganssle commented on pep-9999.rst
> +      sys_paths: list[str]
Generally speaking, I don't use concrete containers, and we definitely shouldn't use them here. This should be `Sequence[str]` and the `dict` ones should be `Mapping`s.

2021-06-02 20:50 UTC, pganssle commented on pep-9999.rst
> +  class RequiredEditableInfo(TypedDict, total=True):
The prose above calls this `EditableInfo` but this is called `RequiredEditableInfo`.

2021-06-02 20:50 UTC, pganssle commented on pep-9999.rst
> +The function returns an object of type ``EditableInfo`` as defined below:
It might be worth adding an "Open Item" where instead of returning a structure like this, we build a wheel-like file that simply contains this information in some serialized form.

Another option would be to have two hooks, one that returns this structure and another that builds a wheel-like object.

2021-06-02 20:50 UTC, pganssle commented on pep-9999.rst
> +Build frontend requirements
This distinction between "Build frontend" and "frontend" is incredibly confusing and unnecessary. I would merge them.

2021-06-02 20:50 UTC, pganssle commented on pep-9999.rst
> +This hook MUST return an additional list of strings containing `PEP-508`_ dependency specifications, above and beyond those specified in the ``pyproject.toml`` file. These dependencies will be instal
Also, "These dependencies will be installed when calling the `build_editable` hook" doesn't seem right. It should maybe be "The frontend must ensure that these dependencies are available in the build environment in whcih the `build_editable` hook is called".

2021-06-02 20:50 UTC, pganssle commented on pep-9999.rst
> +frontend requirements
This seems to conflate in a bunch of the backend's responsibilities.

Why do you have the front-end generating the `RECORD` and `dist-info` folders?

My thoughts on this are that an editable install goes like this:

1. Frontend creates the isolated build environment and invokes `build_editable`
2. The backend does everything it normally would for building a wheel *but* instead of zipping up all the files to be installed, it records a mapping of the locations of files that _would have been zipped up_ along with their destination in the wheel file.
    
    The final structure could be a file on disk or it could be a dict-like structure where the `EditableInfo` dictionary is one sub-part. For example:

    ```python
    {
      'dist-info': {
        'RECORD': <full-text>,
        'LICENSE': <full-text>, 'Wheel-version: ...'
      },
      'package_contents': <some_editable>
    }
    ```

    The only reason to do it as an in-memory format like this is that, basically, since it contains no files on disk and all the metadata is likely generated _in memory_ anyway, we can probably save some time and disk write cycles by directly communicating the information. Another option might be to just allow returning an open file-like object.

3. The front-end takes this information and installs all the metadata parts of the wheel as normal, and in place of the package it does whatever it's going to do to ensure that *at least* all of the relevant paths are exposed in the right places.

Almost all of these pieces are basically what each tool was already doing, with the exception that the backend now needs to keep track of where stuff came from and the frontend/installer needs to have a mechanism for creating some sort of active link to the original locations rather than simply unpacking the file in question.

2021-06-02 20:50 UTC, pganssle commented on pep-9999.rst
> +Author: Bernát Gábor <gaborjbernat@gmail.com>
I suppose if you'd like I can be a co-author on the PEP.

2021-06-02 20:52 UTC, pganssle commented on pep-9999.rst
> +      import_callback: ImportCallback | None
What is this? This seems very complicated and unnecessary. I think it should be removed.

2021-06-03 09:14 UTC, gaborbernat commented on pep-9999.rst
> +frontend requirements
> Why do you have the front-end generating the `RECORD` and `dist-info` folders?

The `RECORD` is a list of files that get installed into the target interpreter and serves as information for the frontend as to what files need to be removed during uninstallation. Considering the frontend is the only one knowing this (because it's derived from the dist-info plus the mappings passed on) only the frontend has all the information available to generate this.

2021-06-11 11:06 UTC, closed without merging